### ISSUE TITLE
SMA: Layer 2 is visualized. Not mentioned anywhere.

### ISSUE THREAD

**Issue by przell** [Eurac-Research/ado-data#1]
For the SMA the layer 2 is visualized currently (see here: https://gitlab.inf.unibz.it/ado/ado_portal_update/-/blob/main/tools.py#L274). 
This is 7-28 cm. 
This info needs to be added in the description when clicking on the info sign.

**Comment by tiacop** [comment]
Please just add this information to the metadata file https://github.com/Eurac-Research/ado-data/blob/main/json/nuts/metadata/SMA.json in the "abstract" section.
