### ISSUE TITLE
Timeseries Viz: VHI/VCI vs Meteo Indices

### ISSUE THREAD

**Issue by przell** [Eurac-Research/ado-data#11]
@tiacop, @aljacob, @masawdah, 

currently we're showing vhi/vci and the meteo indices together in one plot. Which is good - to have the possibility to overlay the different types of indices.

The problems are:
- Timerange of times series
  - we limited all the time series to range only back to 2020 to have a coherent view. -> We are hiding 80% of the data because of two collections that start in 2020 - whereas all the otherst start in 1978
  - I think we agreed to that at some point, but using the platform myself now, I'd argue to rethink this decision
  - How to display the information gracefully is up for discussion. My preferred solution would be to have the view always start at 2020, but with the possibility to zoom around from there (also backwards).
- vci/vhi are on a different scale (0-100) the meteo indices ca -4 - 4.
  - I'd suggest to introduce a second Y-[Axxis](https://www.youtube.com/watch?v=ejFvNtXpT3A&t=14s) for vci/vhi and set 50 equal to 0 of the meteo indices

**Comment by tiacop** [comment]
hey @przell,

* added a second y-axis to the timeseries
* added a dataZoom component with a dynamic default (last available day - 365 days ... could also be minus 2 years or 3)
* added a color-palette with 14 colors to have distinct color for each indicator 

Check it out in the dev branch preview https://ado-git-dev-eurac.vercel.app/

The dev branch preview  now fetches the ado-data dev branch. So we can test dev-data and dev-frontend. 
@masawdah can you push the timeseries with different ranges (for example spi, spei ... 30 years, vci/vhi only 3 years) so we can check if the idea with the dataZoom works.

**Comment by przell** [comment]
@tiacop, this is great! exactly what we were looking for! Maybe we'll have an iteration about some minor things - but this is perfect for our need! Thanks for checking that out so quickly!
Now let's see how it looks with the different time ranges indeed, @masawdah

**Comment by masawdah** [comment]
Ciao @przell @tiacop, I've fixed null values for VCI and VHI for the entire time series, and have pushed the complete time series for all indices, starting from the following dates:

- VCI & VHI:  01-01-2001
- SMA: 01-01-1981
- Other indices: 01-01-1979

It's important to note that the size of the JSON files has increased significantly, jumping from 325 KB to 3596 KB.

**Comment by tiacop** [comment]
hey @masawdah, cool! 
You are right regarding the file size, but ...
it's just text and can be compressed very well - the original 3.5MB JSON has a compressed size of around 250 kB, so "only" 250 kB are shipped to the client. And we load only one timeseries JSON at the time after the user clicks on a region. 
In my opinion it's OK to have the complete series.

@przell @aljacob Preview available at https://ado-git-dev-eurac.vercel.app/. I would increase the default visible timeslot from 1 year to 3 years and merge dev into main and bring the new features on production. What do you think? GO or WAIT?

**Comment by przell** [comment]
@masawdah - thanks for updating the timeseries directly!
@tiacop - looks great, It's a lot better than before. No reason to wait in my opinion! I will  add the doi and fact sheet links to all metadata items as we had tested here (#12). I will contact you when I'm ready so that you can update, with all major changes included!

**Comment by przell** [comment]
@tiacop, closed the activity here https://github.com/Eurac-Research/ado-data/issues/12, 
So ready to be pushed to live, evaluated and closed.

**Comment by tiacop** [comment]
closed by #13
