### ISSUE TITLE
Link to Factsheets on Webplatform

### ISSUE THREAD

**Issue by przell** [Eurac-Research/ado-data#12]
@aljacob, @tiacop, 
In the ADO project fact sheets were produced for the indices that we are showing. I think it would be a pitty not to show them on the webplatform, because they contain valuable information and are designed nicely as well.
@aljacob, can you confirm that the final version of the fact sheets is here: `ADO Sharepoint / Documents / T1 / Factsheets / Final`
@tiacop, could you let me know where in the repo to store the fact sheets? They are PDFs that should be linked in the "About the data" section. I suggest with a new sub-header under drought indices: "Factsheets"

**Comment by przell** [comment]
@tiacop, could you give me the rights to edit the repo? then I'd do the work - according to your idea where to create the folder and how to call it.

**Comment by tiacop** [comment]
hey @przell, you should have all the rights to edit the repo ... you have the role "maintain" for ado-data, next role would be "admin" ... .

I would suggest to create a folder "factsheets" on toplevel, put pdf there and link them on the about page.

An addition could be to show the factsheet link also in the timeseries and the info text. We have done this for DOI by adding the doi to the metadata json. A lonely  example for spi-1 already exists. See shots

<img width="807" alt="image" src="https://user-images.githubusercontent.com/61466670/223681072-78911d4d-2dc4-4788-9f0d-4a99d1e39ade.png">

<img width="678" alt="image" src="https://user-images.githubusercontent.com/61466670/223681185-ff85cda2-677a-4bf6-ab5d-536481964c69.png">

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/61466670/223681480-fb8881c6-ba98-4f86-a6ec-a56dacb74cb4.png">

We could do the same for the factsheets and add the url to a new field "factsheet" in the metadata json files. What do you think?

**Comment by przell** [comment]
@tiacop, hi, 
I have done the following:

- [create folder factsheets](https://github.com/Eurac-Research/ado-data/commit/bff1f954b538ddd9e65fab9be0fb70548d5393f8)
- [uploaded factsheets](https://github.com/Eurac-Research/ado-data/commit/d3855ad211edb02a607d0ac0ba73bf4912d351d9)
- [added fact sheet links to about-the-data.md](https://github.com/Eurac-Research/ado-data/commit/4203ef7377ea3c59d047f032192b76a9070187bd)
- [update metadata SPI-1 with field factsheet](https://github.com/Eurac-Research/ado-data/commit/a64d7bd65712de9e267916e85b65b13cf5b29d10)

I guess what's missing is:
- use the field "factsheet" from SPI-1 metada in the timeseries plot and the info button
- Add the filed "factsheet" (and "doi") to the other metadata files and include them in timeseries and info button

**Comment by tiacop** [comment]
@przell awesome!

I just implemented it on dev https://ado-git-dev-eurac.vercel.app/spi-1 (info plus timeseries).
You are right, what is missing is to add "factsheet" and "doi" to all the metadata file.

And one suggestion, if you change the factsheet URLs from
https://github.com/Eurac-Research/ado-data/blob/main/factsheets/SPI_4.pdf
to 
https://raw.githubusercontent.com/Eurac-Research/ado-data/main/factsheets/SPI_4.pdf
you access the file directly. Maybe a better experience for the user.

**Comment by przell** [comment]
@tiacop, thanks for the feedback and the quick deploy! 

- I have changed the links in the about the data to the raw ones: [fact sheet link to](https://github.com/Eurac-Research/ado-data/commit/20d43e545d3c831622d38480a9a093ce6aa55fcb) https://raw.githubusercontent.com/
- I've updated the one for SPI-1 for ts and info: [meta fact spi1](https://github.com/Eurac-Research/ado-data/commit/e17ff220c848adf5b972c395636ebc954f185fc5)
- I've added factsheet to SMA ts and info: [fact sma](https://github.com/Eurac-Research/ado-data/commit/4fabf11aae7d4c349622e02d536538044f3a5449)
  - But not sure how this will be picked up, because the field doi is not available there, and we don't have an doi for this collection - let's check the behaviour. And then we can finalize.

**Comment by tiacop** [comment]
hey @przell,
I fixed the urls (deleted the "/blob" from the factsheet urls https://github.com/Eurac-Research/ado-data/commit/a10483d33340c78cb49bdb79784bdb8e194e12cd) and merged with the main branch. Also the website code on main branch is pushed ... the features are live. 

Regarding missing doi field, no problem. If there is a doi or a factsheet or both we simply show it ;) See the SMA example with just the factsheet. Looks good to me. https://ado.eurac.edu/sma

**Comment by przell** [comment]
@tiacop, added the missing doi and factsheet links to all collections where available in: `ado-data/json/nuts/metadata`
Once pushed to live and checked, we can consider this closed 📕

**Comment by tiacop** [comment]
closed by #13
