### ISSUE TITLE
Date of VHI on disk and on webmap don't match

### ISSUE THREAD

**Issue by przell** [Eurac-Research/ado-data#14]
@masawdah, Hi, 
I have just seen that the date of vhi/vci we have on disk and the date displayed in the webmap don't match.
We have DOY 105 of 2023 on disk, this is 15.04.2023. On the webmap the most recent date that can be chosen for vhi/vci is 14.04.2023.

![image](https://user-images.githubusercontent.com/51962348/235091518-6c99b922-eca9-47c4-91f9-eca69d5dd792.png)

**Comment by tiacop** [comment]
hey @masawdah and @przell , 
I just had a look and saw that for a few indices (for example https://raw.githubusercontent.com/Eurac-Research/ado-data/main/json/nuts/SPEI-3-latest.geojson) the "lastDate" value (today this value is "2023-04-21")  does not match the real last day in the file (if you search for "2023-04-22" you get 272 results) ... I think this is the reason for other problems too (strange lastdate in the timeseries view ...).

**Comment by masawdah** [comment]
Solved. All the dates are sorted and matched.
